### ISSUE TITLE
New Parser/Renderer

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#1093]
Future updates and fixes for current bugs is becoming more difficult due to the current structure of the Markdown->HTML->Render pipeline. This is partly due to unforseen consequences of early design choices, layers of patches and band-aids, and users with custom styling and HTML. We propose creating a new "V2" pipeline which will become the new default, leaving behind the current implementation as a "legacy" option so as to preserve older brews, but limiting further updates on that path. We have learned a lot as the Homebrewery has grown and become more popular, and it is time to put it to use in a new, better version.

This issue will collect the sub-tasks and related issues.

Note: @stolksdorf did ~a lot of~ almost all of this work already, and even totally cleaned up and organized everything. The [NewRenderer](https://github.com/naturalcrit/homebrewery/tree/newRenderer/shared/homebrewery) branch is a goldmine. Some of it might not be compatible with the current codebase, but I really like what he's done.

### Create new render pipeline, "V3"

- [x] Collect legacy code into separate "legacy renderer" pipeline
- [x] Add "Homebrewery Version" tag to brews ("legacy" or "V3")
- [x] Switch between render pipelines based on Version tag
- [x] Update Markdown version for new pipeline (#852) 

### Restructure PHB Styling
- [x] Implement CSS Div classes in Markdown (#403)
  - [x] Define formatting (mustache-like vs Pandoc fenced divs, etc.)
  - [x] Add CodeMirror highlighting to the mustache syntax
- [ ] Update styling and rebuild Snippets to use mustache syntax instead of janky Markdown combinations
  - [x] Standard paragraph text
  - [x] Headers
    - [x] H1
    - [x] H2
    - [x] H3
    - [x] H4
    - [x] H5
  - [x] Drop caps (fancy first letter)  
  - [x] Monster stat blocks #509
    - [x] Standard
    - [x] Wide
    - [x] Border-less   
  - [x] Tables
    - [x] Standard table
    - [x] Wide table
    - [x] Split table
    - [x] Class table
    - [x] Half class table
  - [x] Note box
  - [x] Descriptive box
  - [x] Spell
  - [x] Spell list
  - [x] Class feature
  - [ ] Cover page
  - [x] Vertical spacing
  - [x] Column break
  - [x] Page break
  - [x] Wide block
  - [x] Image
  - [x] Background image
  - [x] Page number
  - [x] Auto-incrementing page number
  - [x] Link to page
  - [x] Table of Contents #304
  - [x] Tweak drop cap
- [x] Update to latest version of Marked.js for more accurate parsing (and fewer weird bugs)
- [x] Use /column instead of code fences for column breaks
- [x] /column and /page must occur alone at beginning of a line to prevent accidental page breaks (#1147)

**Comment by Gazook89** [comment]
I saw mention somewhere that the new version won't allow direct html, and for awhile i've been wondering if that is 100% true, or if it just won't allow _some_ html?  Can you confirm either way, and what html tags might remain available (or become not available)?

**Comment by calculuschild** [comment]
We will still allow HTML. I think there are way too many people out there who love the Homebrewery precisely because of how customizable it is (including me).

However, we will no longer "support" raw HTML. Meaning, if something breaks because you have bad HTML, we aren't going prioritize pushing out code fixes to make sure your custom thing works.

We have gone a long way towards preventing random crashes, etc. from custom HTML, but at some point it's beyond the scope of the Homebrewery's goals. Plus, if we can encourage and supply everything 95% of people need just with Markdown, I think that lowers the barrier to entry for a lot of people who don't necessarily know the difference between HTML and Markdown or any computer language at all.

**Comment by Gazook89** [comment]
[Is this 2017 post by Stolksdorf ](https://github.com/naturalcrit/homebrewery/issues/395#issuecomment-301109478) basically the foundation of the new renderer?  The curly braces "divs" and such?  Just happened across it and thought it is a well reasoned argument.  Particularly the concern about moving from "photoshop expertise to coding expertise" and the issues around that.  

Maintaining divs was my biggest concern, and the "blocks" will do that.  If this is the route forward, that is good to know because I will start to think about writing my guides (and possible snippets) with that in mind.

**Comment by calculuschild** [comment]
Yep, that's where it comes from. He even posted 90% of the work already here on Github, but just didn't quite get the final bits finished to publish it. There are a lot of good reasons to make the changes.

Now, my understanding is he wanted to fully remove any HTML capabilities, which we could do, but I don't know if such a drastic restriction is for the best. There are a few cases such as with `<br>` or even custom tweaks in tables that would no longer be possible. But maybe this can be a part of the "beta" phase as people opt in.

What we might start with, though, is removing the janky code that renders markdown inside of other HTML. Normally, `<div> **bold** </div>` would not recognize the markdown inside the Div, but we made special code to allow that (and it has weird unexpected consequences unfortunately).  So if you want a block of custom HTML, it would require HTML only for everything inside as well.

**Comment by Gazook89** [comment]
I see that "class table" is ticked as complete on the above list-- i just inserted a class table in v3 and it still comes up using divs rather than moustache syntax.  just fyi.

**Comment by calculuschild** [comment]
Class table is not ticked is it?

**Comment by Gazook89** [comment]
ugh, sorry, ignore me....i think i looked at monster stat blocks by mistake.

**Comment by Gazook89** [comment]
Close this bad boy out?  Cover Page snippet never got done, but let's lump that together with a new issue regarding "Page Layout" snippets as mentioned in #781.

Leaving to @calculuschild for the cathartic release.

**Comment by calculuschild** [comment]
...yeah... I guess... It's done isn't it? :finnadie:

Ooo-weee.

Yep, let's move cover page to the new issue and close this out.
