### ISSUE TITLE
Fill out missing style snippets

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#1096]
Once the new rendering pipeline is in place, we can start inserting more requested code snippets and styling features that users have created or requested for a long time. Part of the reason these have not been added until now, is the over-dependence on random markdown combinations to create textboxes, which leads to lots of conflicting styling issues in the CSS. Further, the use of invalid markdown due to an outdated markdown parser makes these conflicts even more common.

Blocked by #1093. Once that is complete, more of these tasks can be finished out.

This issue will collect the sub-tasks and related issues.

### Clean up existing styling and snippets
- [x] Inconsistent list font size in block quotes #1085
- [x] Background decoration on Class Table #302 

### Include snippets for common missing PHB items
*(collect from issues, a lot of these are already figured out)*
- [x] Table of Contents
- [x] Title page #640, #1334
  - [x] Add title fonts #2061
- [ ] Adventure Flowchart #936 
- [x] Monster Stat Block without Box #914 
- [ ] Notes on paper scraps (probably best handled by user images) #826 
- [x] Third-caster class table #1079, #191 
- [x] Magic Items #842, #671 
- [ ] ...etc.

### Include snippets for user convenience
*(collect from issues)*
- [x] Code style (often used for tutorial documents here)
- [x] QR Code #539 
- [ ] Credits to Homebrewery #283 

### Correct other existing style bugs
- [x] Line spacing in bulleted lists is inconsistent #1120
- [x] Long words are not wrapped #1136

**Comment by Gazook89** [comment]
The "Page Number" snippet contains both a page number component and a 'footer' component, and I think they should be separated....or, the footer component be added to the "Auto Incrementing Page Number" snippet as well...it's weird that the footer is in one, but not the other.

**Comment by calculuschild** [comment]
I don't mind separating them. That makes sense to me.

**Comment by calculuschild** [comment]
User u/Kaiburr_Kath-Hound on Reddit (with help from others) has completed several of these and notified me that he would like to contribute them as official snippets. May need slight tweaks but 95% of the work is done:

https://www.reddit.com/r/homebrewery/comments/qubn28/phbstyle_including_title_page_credits_page/

**Comment by ericscheid** [comment]
No longer blocked by #1093 as [on 12 Sep 2021](https://github.com/naturalcrit/homebrewery/issues/1093#event-5288558482).

**Comment by 5e-Cleric** [comment]
Cover page done in #2649, approval pending.
I have a working demo of a Back Cover in my local, but i would like a help with the snippet text.

**Comment by 5e-Cleric** [comment]
Update on this:

Include snippets for common missing PHB items
(collect from issues, a lot of these are already figured out)


- [ ]  Title page https://github.com/naturalcrit/homebrewery/pull/2649 
- [ ]  Adventure Flowchart https://github.com/naturalcrit/homebrewery/issues/936
- [ ]  Notes on paper scraps (probably best handled by user images) https://github.com/naturalcrit/homebrewery/issues/826
- [ ]  Inside Cover
- [ ]  Parts Covers
- [ ]  Back Cover
- [ ]  Credits page
- [ ]  Script table
- [ ]  ...etc.
- [ ]  index

**Comment by 5e-Cleric** [comment]
Closing, as track of snippets will now be kept in #3236
