### ISSUE TITLE
Split CSS styling to separate panel

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#1137]
The editor will be split into two tabs, the default Markdown editor panel, and a second CSS styling panel. This will serve multiple purposes:

1) Allow users to clean up brews which use large amounts of custom styling
2) Facilitate swapping styles (not just PHB, but eventually DMG, custom "HB" style, etc.)'
3) Allow users to have a central custom style sheet they can easily import into various documents without having to manage the CSS on each individual document.
4) Allow sharing of custom styling via an importable style sheet.
5) Simplify exporting of custom CSS

Note: @stolksdorf did *a lot* of this work already, and even totally cleaned up and organized everything. The [v3](https://github.com/naturalcrit/homebrewery/tree/newRenderer/shared/homebrewery) branch is a goldmine. Some of it might not be compatible with the current codebase, but I really like what he's done.

Blocked by #1093 

### Create separate Style panel
- [x] Style panel accessible via tab/button
- [x] Document applies any styles inside second panel
- [x] Style panel content is saved in the same text with the brew markdown

**Comment by calculuschild** [comment]
Quote from Gitter:

> I see the Switchable Style Sheets developing in a few steps:
> 1) Split "content" and "style" editor panels.
> 1) Save "content" and "style" as separate, but linked documents.
> 1) Allow "linking" style sheets to existing brews. This way multiple brews can share the same base style sheet.
> 1) Users can now start sharing style sheets with one another. Style sheets will still have a "share" and an "edit" link, so if you linked to the "share" version, you can't go ruin it for everyone else who is using it.
> 1) Hopefully some users will be willing to "donate" their styles for us to provide as an official supported style which is accessible via a menu/snippet.

**Comment by ericscheid** [comment]
The current inline method of `<style>` would continue to be available, I would hope. I have a habit of dropping style blocks near the targeted content — for ease of fiddling, easy recognition of what is making that particular brew content look different, and easy location of the CSS to edit (vs. scrolling up and down through a long separate document).

I would suggest that the easiest way of # 3 in your list would be by just writing something like this:

```
<style>
@import url("/style/mumble");
</style>
```

.. where `/style/mumble` is the share link in your # 4. Maybe not that route, but something that we can key off to ensure we send the right Content-type header value.

Actually, with your # 2 item .. if we save the brew.content and the brew.style (from your # 1 point) into the same mongoDB document, and thus there's the one shareID for both .. but we just use the route to select whether we return the plain css or the fully rendered html content. And in that bit of elegance we also now have a brew.content that can act as documentation for the brew.style.

- http://homebrewery.naturalcrit.com/share/mumblesoup -- this is the brew rendered as html
- http://homebrewery.naturalcrit.com/style/mumblesoup -- this is just the brew.style returned as Content-type: text/css

**Comment by calculuschild** [comment]
> The current inline method of <style> would continue to be available, I would hope.

Yes, it will still be available. Scattering style tags throughout the document does lead to some CSS weirdness (`<style>` can get picked up by a CSS selector and cause unintended spaces or interactions, and we have to render EVERY page that has a style tag so it gets applied to the CSS, instead of only rendering the visible page, which gradually slows down the program). So we will encourage a separate style sheet but users can do what they want.

> if we save the brew.content and the brew.style... and thus there's the one shareID for both

We could also go that route, but it does make it harder to work with Google Docs for instance, since there's not a separate field that we can use for a large block of text. We would need some format to merge it all together into one text file.

**Comment by calculuschild** [comment]
@stolksdorf had this to say back in 2018 on Gitter:

A single gist can store multiple files within, if we want to separate them apart. I see three major pieces of data for a brew, the metadata (in json/yaml), the markdown, and custom css. I want to drop storing custom css as style tags within brews, it's messy and breaks partial page rendering. Plus we can make a separate css editor with accurate syntax highlighting.
I've used metamarkdown to store front matter in markdown before and it works great
https://stackoverflow.com/questions/44215896/markdown-metadata-format
it also renders well when viewing the markdown file in standard renderers

![image](https://files.gitter.im/naturalcrit/Lobby/glMP/image.png)

![image](https://files.gitter.im/naturalcrit/Lobby/AgXr/image.png)

This is an example of how we might mix the three bit of data into a single text file.

``````
---
description: my scary monster
tags: 5e, monster
format: a4
theme: phb
---

```css
.spell{
  font-weight : 800
}
```

# My Scary Moster

...
``````

the new editor should have three tabs, one of each part of data: The markdown editor, a css editor, and a settings tab to update the metadata about the brew. So the general user wouldn't directly interact with the storage format, just each of it's parts.

**Comment by ericscheid** [comment]
Presumably a single brew could pull from multiple shared css resources too, right?

**Comment by calculuschild** [comment]
Complete! Added in #1385
