### ISSUE TITLE
[UserPage] Change order of Published/Private Brews

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#1797]
As mentioned in [this Reddit comment](https://www.reddit.com/r/homebrewery/comments/qlh2hn/bug_sorting_by_views_not_really_sorting_by/hj4p8jr), some users would like to be able to re-order the groups on the User Page, as they do not edit Published brews, which are listed at the top of the page. Having the ability to push this group to the bottom of the page would improve their user experience.

**Comment by ericscheid** [comment]
Or perhaps provide a widget to collapse the section?

**Comment by G-Ambatte** [comment]
Collapsing is probably easier to implement than re-ordering.

![](https://c.tenor.com/ZezsFuiFB48AAAAd/both-is-good-both.gif)

**Comment by G-Ambatte** [comment]
Current state of the PR:

![image](https://user-images.githubusercontent.com/19826659/187066250-50d61268-d13e-436e-a892-cc4d6bb3a4d9.png)

- [x] Mousing over the title changes the pointer to a hand.
- [x] Clicking the header toggles the visibility state.
- [x] The state indicator to the left of the header changes to indicate when items are hidden.
- [x] Visibility selections are stored in/retrieved from local storage

I haven't drafted the PR yet as there's still a lingering error in the console, but the current work is in my fork: https://github.com/G-Ambatte/homebrewery/tree/addUserPageCollapse-%231797

**Comment by G-Ambatte** [comment]
I think this is in a good place now, I'll raise a PR for review.

**Comment by ericscheid** [comment]
Looks good.
