### ISSUE TITLE
Chrome Bug Tracker

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#1813]
We have several little issues that are due to bugs in Chrome that are awaiting fixes. Just recording them here so we can track when they are solved and send people over to star them.

### Active

- [ ] **Using `drop-shadow` converts text to an image instead of selectable text in the PDF**
  - [Chrome Bug Tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=1255243)
  - Related issue: #1661
- [ ] **CSS translateZ() is ignored in the PDF, making background "decoration" appear on top**
  - [Chrome Bug Tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=1265296)
  - Related issue: 
- [ ] **Clipped background images cause excessive PDF size**
  - [Chrome Bug Tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=910588)
  - Related issue: 
- [ ] **Each page creates a separate copy of the background image in the PDF, leading to large files**
  - [Chrome Bug Tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=1196526)
  - Related issue:
 - [ ] **Top and bottom of box borders are cut off at column breaks**
   - [Chrome Bug Tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=829028), [Chrome Bug Tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=1193966)
   - Related issue:
- [ ] **Box-shadow renders as a solid box in PDF when viewed with Mac Preview**
  - [Chrome Bug Tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=995265)
  - Related issue:

### Solved:

- [x] **Second element in two-columns layout shifted to second column in PDF**
  - [Chrome Bug Tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=1006249)
  - Related issue:
 - [x] **PDF is missing random characters from certain fonts**
   - [Chrome Bug Tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=926885), [Chrome Bug Tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=928718)
   - Related issue:
- [x] **Transparent shadows don't render at all in PDFs**
  - [Chrome Bug Tracker](https://bugs.chromium.org/p/skia/issues/detail?id=237), [Chrome Bug Tracker](https://bugs.chromium.org/p/skia/issues/detail?id=1431)
  - Related issue:
- [x] **Transparent shadows appear as solid boxes in PDFs**
  - [Chrome Bug Tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=127651), [Chrome Bug Tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=174583)
  - Related issue:

**Comment by 5e-Cleric** [comment]
They are no longer stars, the button is now a +1, even though they are still called stars elsewhere.

![Image](https://github.com/user-attachments/assets/47562f75-5ac9-4338-a552-20eb5f3851bf)

**Comment by G-Ambatte** [comment]
I've been experimenting with a work around for the shadows=>grey box issue, because it doesn't seem to be going away - see the styling here:
https://homebrewery.naturalcrit.com/share/H8lmhcqi75KA

**Comment by calculuschild** [comment]
> I've been experimenting with a work around for the shadows=>grey box issue, because it doesn't seem to be going away - see the styling here:
> https://homebrewery.naturalcrit.com/share/H8lmhcqi75KA

If this is drop-shadow vs box shadow, we already attempted this years ago and it leads to more problems than it fixes. Ended up having to revert it.

**Comment by 5e-Cleric** [comment]
should add #3656
