### ISSUE TITLE
[Documentation] Offline Install Instructions: Ubuntu

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#1900]
Sub-epic of #1896 - Document the installation process required to get Homebrewery running on Ubuntu.

- [x] Get Homebrewery working on Ubuntu
- [x] Document requirements
- [x] Create install script
- [x] Create README.UBUNTU.md
