### ISSUE TITLE
[Documentation] Offline Install Instructions: Debian

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#1902]
Document the installation process required to get Homebrewery running on Debian.

- [x] Get Homebrewery working on Debian
- [x] Document requirements
- [x] Create install script
- [x] Create README.DEBIAN.md

**Comment by G-Ambatte** [comment]
Initial attempts to get Homebrewery working on Debian 11 (bullseye) have failed due to issues with MongoDB not working. However the MongoDB install instructions (at https://docs.mongodb.com/manual/tutorial/install-mongodb-enterprise-on-debian) indicate that Debian 10 (buster) _IS_ supported, so I am shifting my efforts to that version of the distro.

**Comment by G-Ambatte** [comment]
After some difficulties, I have Mongo working in Debian 10. However, these difficulties lead me to believe it was a VM setting that was the issue in Debian 11, not an internal software issue. I intend to continue with Buster, but will return to try Bullseye again afterwards.

**Comment by G-Ambatte** [comment]
## Installing MongoDB

https://docs.mongodb.com/manual/tutorial/install-mongodb-on-debian

1. `wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -`

2. `echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/5.0 main" | tee /etc/apt/sources.list.d/mongodb-org-5.0.list`

3. `apt update`

4. `apt install -y mongodb-org`

**Comment by G-Ambatte** [comment]
## Installing NodeJS v16

https://github.com/nodesource/distributions/blob/master/README.md

1. apt install -y curl

2. curl -fsSL https://deb.nodesource.com/setup_16.x | bash -

3. apt-get install -y nodejs

**Comment by G-Ambatte** [comment]
I shifted back to Bullseye, so these steps are for Debian 11. Most of them need to be run as `root`; I have not noted specific `sudo`s as my intention is to include these steps into a script which will be run as root. In general, these steps are very similar to the Ubuntu instructions.

### Add Node v16 source
1. `apt install -y curl`
2. `curl -fsSL https://deb.nodesource.com/setup_16.x | bash -`

### Add MongoDB source
3. `wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | apt-key add -`
4. `echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/5.0 main" | tee /etc/apt/sources.list.d/mongodb-org-5.0.list`

### Install requirements
5. `apt update`
6. `apt satisfy -y git nodejs npm mongodb-org`

### Enable and start MongoDB
7. `systemctl enable --now mongod`

### Install Homebrewery files
8. `cd /usr/local`
9. `git clone https://github.com/naturalcrit/homebrewery.git`
10. `cd homebrewery`
11. `npm install`
12. `npm audit fix`
13. `npm run postinstall`

### Set NODE_ENV
14. `NODE_ENV=local`
15. `export NODE_ENV`

### Start Homebrewery server
16. `node server.js`

**Comment by G-Ambatte** [comment]
Going through these steps has made me realize that the Ubuntu install script may be installing an unofficial MongoDB package instead of the official release. I'll look into it and raise it as a separate issue if that's the case.

**Comment by G-Ambatte** [comment]
> ### Add MongoDB source
> 
>     3. `wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | apt-key add -`
> 
>     4. `echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/5.0 main" | tee /etc/apt/sources.list.d/mongodb-org-5.0.list`

By adding these lines to the Ubuntu install script, the script completed successfully on Debian. My understanding is that the Ubuntu install script currently installs an unofficial, unsupported version of MongoDB, whereas these steps add the official MongoDB Community package, so these steps should be added to the Ubuntu install script. By doing so, the install script should become compatible with both Debian 11 and Ubuntu 20.

**Comment by G-Ambatte** [comment]
While the script may result in a functional system in both Ubuntu and Debian, given that MongoDB maintains two different sets of install instructions, it would be more appropriate to maintain two different install scripts.

**Comment by 5e-Cleric** [comment]
Closing in favor of #4678, this isssue even closed will retain the comments so there is no loss of information.
