### ISSUE TITLE
[UserPage] Minor Fixes - Checklist

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#2295]
User page changes:

- [x] show current tags in BrewItem (mimic current author listing functionality?) (#2317 / #2318)
- [x] expand filter to include tags (#2319 / #2320)
- [x] add URL parameters for sort by and direction ( #2315 / #2316)
- [x] save sort by & direction to local storage; load and use when page loaded with no URL parameters present (#2326 / #2327)
- [x] loading page with filter URLParameter does not apply filter to page (#2297)
- [x] ~~show current system tags (#1842 / #2330)~~ 
- [x] rework sorting options, possibly add page count to sorting options (#1796 / #2379)
- [x] remove autofocus from User Page (#2121 / #2305)
- [x] add section collapsing and/or reordering ( #1797 /  #2300)
- [x] show thumbnail from metadata (if not blank) ( #2331 /  #2332)
- [x] fix centering of SortContainer when scroll bar hidden ( #2303 / #2304; follow up #2352 / #2360 & #2382)
- [x] switch to v3 CSS (#2301 / #2302)
- [x] smarten possessive apostrophe in `usernameWithS` (replace `'` with `&rsquo;`) (#2328 / #2329)

**Comment by ericscheid** [comment]
- [ ] show thumbnail from metadata (if not blank)

**Comment by ericscheid** [comment]
- [ ] fix the centering of the sortcontainer

<img width="938" alt="image" src="https://user-images.githubusercontent.com/2605467/187063453-83773f01-9fbc-449b-8245-7020de753f28.png">

The current CSS has `left: calc(50vw - 408px)` .. but this fails if the scroll bar on OSX is set to hide.

Another strategy is needed.

**Comment by ericscheid** [comment]
- [ ] Use v3 renderer

Just for sanity sake.

<img width="678" alt="image" src="https://user-images.githubusercontent.com/2605467/187063708-a810795d-acf6-41ad-8b4c-9771cfa9a29d.png">

**Comment by G-Ambatte** [comment]
> * [ ]  Use v3 renderer

It should be trivial to switch over to the v3 CSS - I'll have a quick look at it later today/tonight.

**Comment by G-Ambatte** [comment]
Add all of these to the main checklist.

**Comment by G-Ambatte** [comment]
> smarten possessive apostrophe in `usernameWithS`

Added to the list.

**Comment by Gazook89** [comment]
On my Mac, with Firefox, my user page blue background is only the height of my screen--- it can be scrolled out of view.  

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/58999374/189465725-0c61ab04-8149-4755-9ba8-c4985995db1e.png">


Not sure why this is the case.  Using the dev tools I changed the .sitePage class by removing the `height` property and it fixed it....but it has adverse impact on the editing page (such as the divider bar doesn't render at full height).  This was just some real quick poking around and I don't have a functioning local install anymore.

**Comment by Gazook89** [comment]
Another thing:  The search/filter/sort bar looks...not well, on MacOS FF.  And looking in Dev Tools, it's done as a `<table>`.  I think this would be greatly improved as a flex container.  Centering and responsiveness would be greatly improved.

**Comment by G-Ambatte** [comment]
> On my Mac, with Firefox, my user page blue background is only the height of my screen--- it can be scrolled out of view.
> 
> <img alt="image" width="1265" src="https://user-images.githubusercontent.com/58999374/189465725-0c61ab04-8149-4755-9ba8-c4985995db1e.png">
> 
> Not sure why this is the case. Using the dev tools I changed the .sitePage class by removing the `height` property and it fixed it....but it has adverse impact on the editing page (such as the divider bar doesn't render at full height). This was just some real quick poking around and I don't have a functioning local install anymore.

Dammit, same thing happens on Win 10 FF. Looks like `overlay` isn't a valid value in FF, so the `content` div has no scroll bar, allowing the parent element to scroll instead - which contains the blue background. Damn, I actually thought we had a solution that was working for everyone this time.

**Comment by G-Ambatte** [comment]
> Another thing: The search/filter/sort bar looks...not well, on MacOS FF. And looking in Dev Tools, it's done as a `<table>`. I think this would be greatly improved as a flex container. Centering and responsiveness would be greatly improved.
> 
> <img alt="image" width="876" src="https://user-images.githubusercontent.com/58999374/189465885-bbb14bd8-f2c7-4748-86e3-c75545349e47.png">

Nothing about the content of the sort container has changed in these PRs - at least, not yet. It got tweaked right by 8px with the `overlay` change, but that's the only change that I recall. However, it is in line for a re-work in order to be able to add more sort categories - I'm thinking we use a `:before` element in the same way we've done the visibility icon on the headers to indicate ascending/descending order, and only have it visible on the active sorting type element.

**Comment by Gazook89** [comment]
> However, it is in line for a re-work in order to be able to add more sort categories - I'm thinking we use a :before element in the same way we've done the visibility icon on the headers to indicate ascending/descending order, and only have it visible on the active sorting type element. 

I have a branch now that has the whole sort/filter bar reworked as a series of flex divs, rather than table.  It changes the sort direction to be an icon that appears next to whichever sort option is chosen.  It changes to white when hovered, as well.  The filter text area moves to a second row if the screen size is dramatically reduced (for anticipation of mobile use in the far distant future).   In my opinion it fits better with the UI elements, rather than with the content.

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/58999374/190009588-38ac48cd-a4ee-4280-9173-73aeb9e9ca0b.png">

**Comment by Gazook89** [comment]
> fix centering of SortContainer when scroll bar hidden 

This one can be checked off as complete.

> rework sorting options, possibly add page count to sorting options

This one can also be checked off as complete, too, as far as I'm concerned.  The original linked issue is closed since we decided that page count sorting wasn't really necessary.

Unless there is anything else to add to this list immediately, I think this issue can be closed @G-Ambatte.

**Comment by G-Ambatte** [comment]
As all of the PRs have now been merged and all of the Issues closed, I'll close this as complete!
