### ISSUE TITLE
[EPIC] Admin Pages changes

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#2671]
### Your idea:

This issue is to track the progress of the changes to the Admin Pages and the related underlying systems.

- [x] Fix Admin pages on live site - #2657 
  - [x] PR #2658 raised and ready for merging
- [x] Create Notification DB - #2585 
  - [ ] PR #2586 in progress
- [x]  Create User Info DB - #1908
  - [ ] PR #2474 in progress - currently outdated due to conflicts in `app.js`

**Comment by 5e-Cleric** [comment]
#3264 refactored admin page functions to work with newer syntax, they are working again.

**Comment by 5e-Cleric** [comment]
quoting closed error because it is extremely related:
> Almost none of the admin functions work as they were initially intended, mainly:
> 
> * search of total number of brews always returns a 503 (timeout)
> * search for deletable brews is limited to aprox 0.008% of the current brews database, which is incredibly low, and higher searchess also return 503 (timeout)
> * Not as important but brew by Id should return more info like creation date (relevant 2 days ago to figure out a 2k page brew was 8 days old)
> 
> We also might want to include other functions to get some data, like charting brews by page number, or users by brew number...

**Comment by 5e-Cleric** [comment]
This is all done

**Comment by 5e-Cleric** [comment]
Reopening with some ideas, editing the original message to show the next steps as well as the done stuff.
