### ISSUE TITLE
Personalisation of User Account

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#2995]
The homebrewery will eventually have publicly searchable brews, and you can already go to an author's page via the share pages, so some extra features common to all social media would improve UX, i suggest:

- [ ] User image
- [ ] Profile description <150 char
- [ ] Full page Banner
- [ ] Custom stylesheet for their user page

**Comment by Gazook89** [comment]
In the past we’ve talked about “platform” vs “tool”, and leaned more towards “tool” only. Adding a site-wide search for all brews (marked Published) and building out custom user pages would be a big change in the other direction. I guess either way doesn’t really matter to me personally but just adding that context. 

That said, my current position about user page Stylesheets is to be against them. It just seems like a messy thing, and if a user screws something up there may not be much we can do to help them. Further, they may do stuff that works in one browser but not for all, and then other users who go to that page can’t view any of it (which is worse than one bad brew). The general wisdom has been “don’t encourage/let users alter or mimic existing UI”. This could be mitigated by having a few changeable things accomplished by pre-made inputs (a color selector for choosing font colors for example), but even that I think is a recipe for a chaotic mess of user pages and user experience. 

I do think they a bio spot is low effort and without any issue, and same with a user pic for those people with established logos (and anyone else). I don’t think they are tremendously necessary, but might be nice-to-haves.

**Comment by lucastucious** [comment]
Agreed on the stylesheet : don't let user go crazy on a page that someone will visit expecting neutrality. 

But for media sharing, a banner or a account pic could be great

**Comment by dbolack-ab** [comment]
I am inclined to think this should be a NaturalCrit issue, not Homebrewery.

**Comment by 5e-Cleric** [comment]
I agree to a point, but brews are shown in their homebrewery userpage, unless we want to change this..

I guess we could display in the homebrewery profile page an image set in the naturalcrit page.. if that makes sense

**Comment by 5e-Cleric** [comment]
The agnostic theme will be more suited really, closing this as not planned
