### ISSUE TITLE
Search published brews

### ISSUE THREAD

**Issue by RexDraconum** [naturalcrit/homebrewery#697]
Not an issue per se, but my family's security software blocks Reddit, so I can't post this there. 

It says under the publish button that eventually published brews will be publically viewable and searchable. Is that going to be soon, or is it still a long way off?

Kind regards, RexDraconum

**Comment by ericscheid** [comment]
We're building a roadmap, this is a candidate.

Won't be real soon, but likely sooner than some other epics.

**Comment by ericscheid** [comment]
We are interested in everyone's thoughts on what form this functionality would take?

Obviously we have the UI for nominating a brew for publishing .. but what would the "publically viewable and searchable" UI look like? What options for searching?

**Comment by Gazook89** [comment]
I suspect that this would tie into a more robust "website" portion of the project, outside of the editor, and push HB closer to the GM Binder experience.  Likely it should be it's own github 'project'?

Some ideas to start with:
- Homepage outside of the editor that contains:
  - widget featuring 'hot' brews  (gaining a certain numbers of visits within last 12 hours or similar, or even a dropdown menu to choose a time period.)
  - ability to browse all published brews, with filters on system (5e, 4e, pathfinder, etc), number of pages, legacy or v3...
  - search function that searches only within users or brew titles (as listed in the metadata)
  - widget with 'random brew of the day'
  - maybe add an 'upvote' system in addition to just views...but I would say that 'downvotes' are not necessary.
  - a 'flair' or tagging option beyond just the game systems, such as 'tutorial', 'monster', 'spell', 'campaign', etc.

- Or maybe more simply, a drop down toolbars
  - with a search box 
  - a category selector (using those same tags)
  - left and right arrow buttons that move you along to different brews randomly, within that category.

**Comment by ericscheid** [comment]
Side note: the homebrew data model and UI does include a "tags" field, but it is commented out and undeveloped.

There is interest in tags for organising reasons too. #758

**Comment by G-Ambatte** [comment]
> Side note: the homebrew data model and UI does include a "tags" field, but it is commented out and undeveloped.
> 
> There is interest in tags for organising reasons too. #758

I was just thinking about that; I have about a dozen brews that I made to help out someone in the subreddit; I've taken to giving them a title that starts with "Example:" so that they appear in one place in the list, but it'd be even better if I could dump them in an "Examples" folder where I don't actually have to look at them.

---

Along the same lines as already mentioned: searchable public content, newest brews, recently updated public brews, favourite brews/creators, notification when favourited brews are updated or favourite creators release new content (possibly in the navbar, when logging in or refreshing the site), user likes/upvotes driving "hot content", creator bios on user pages with social media links/integration (link to YouTube/Twitch, options to post Brew release notification to Twitter/FB). Admittedly, probably getting to the thin edge of the project roadmap there.

One concern I will mention with providing a platform for user content is the possibility of inappropriate content; it is likely that a reporting system will need to exist, because people love to complain because **WON'T SOMEONE THINK OF THE CHILDREN.** It's also possible that for legal reasons an auditable process for DMCA takedown requests will need to be available, because many people seem to think that "appears in Google Image search" is the same as "royalty free content", and the last thing any FOSS project needs is legal grief.

**Comment by jeddai** [comment]
I definitely agree a reporting feature would need to exist. One thing to note is instead of it sending an email to someone when a brew is reported it could instead use a webhook to send a message to a Slack workspace, discord server or a self-hosted alternative. That would be able to keep smtp/paid email API services out of this.

**Comment by ericscheid** [comment]
> a webhook to send a message to a Slack workspace, discord server or a self-hosted alternative

or even raise an issue on this github.

**Comment by ericscheid** [comment]
Not mentioned anywhere above: all brews are publically viewable via their `/share` and `/edit` URLs. 

The "published" status doesn't affect that.

**Comment by jeddai** [comment]
I also just thought about this, but something that users that monetize their content might appreciate is a Patreon integration. 

Creators could authorize their HB account with Patreon, and when publishing brews could mark them as locked behind certain patron tiers they have.

Patrons would also need to authorize with Patreon, but after doing so could visit the creator's page and see all the content available to them based on their subscription tier with that creator. 

I've worked with the Patreon API in the past and it's currently undergoing a pretty big shift, just noting this for the future if the idea seems nice.

**Comment by ericscheid** [comment]
Progress note:

- [x] implement stubs so gdrive published brews will show in published
- [x] implement UI for entering tags
- [ ] everything else to do with publishing

**Comment by ericscheid** [comment]
- https://github.com/naturalcrit/homebrewery/issues/2708 is a blocker

**Comment by 5e-Cleric** [comment]
Well, i took the liberty to ignore the blocked label, and have a working prototype of this function.

<img width="960" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/91662974/4e032a25-5acd-4958-a2a3-a67fc765889d">

I happily say, it works, and i am working on its UI and new functionalities. Progress in #3263.

**Comment by 5e-Cleric** [comment]
### UPDATE

![image](https://github.com/user-attachments/assets/0e22d62a-f97f-45a7-9d15-56040223ab48)

**Comment by 5e-Cleric** [comment]
### Insight for future developers
As a bit of insight for future questions, i am adding here info that may not have been detailed in the PR or in gitter chat.

#### Indexes
We have enabled indexes for this feature, including a compound index of title + published, to improve search efficiency.

Specifically, a search for a term such as "Dragon" as a title, returning 702 results total, takes around 10ms. This is a remarkable improvement from the first draft, which took at best 4 seconds.

#### Why pagination
Because of the initial long times, the queries have been separated into the brews, and the total number.

Also because of the initial long times, dynamic pagination was built, allowing for different sizes of pages. This feature is currently not needed, but is kept to prevent longer times when the database grows in size.

Currently around 4% of the total Brews is published (44k of 1.1M), no brew is published without an author. This and other mongo features mean that no search returns more than 900 results for now.

#### A specific search doesn't work?
A word of advice for people looking for bugs, some small and common words are ignored in the search field, mongo has a list. (https://github.com/igorbrigadir/stopwords/blob/master/en/mongodb.txt)
